/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ycambro.tarea2.ui;

import com.ycambro.tarea2.Aplicacion;
import com.ycambro.tarea2.bd.consultas.*;
import com.ycambro.tarea2.entidades.comidas.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yurgencm
 */
public class MainFrame extends javax.swing.JFrame {
    Aplicacion app = new Aplicacion();
    String sepalo = null;
    Image myIcon = Toolkit.getDefaultToolkit().getImage(MainFrame.class.getResource("/com/ycambro/tarea2/ui/logo.png"));
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        crud = new javax.swing.JFrame();
        textT2 = new javax.swing.JLabel();
        textT3 = new javax.swing.JLabel();
        textCal = new javax.swing.JLabel();
        textPrice = new javax.swing.JLabel();
        nombreA = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        tipo1A = new javax.swing.JTextField();
        textPrice1 = new javax.swing.JLabel();
        updateBot = new javax.swing.JButton();
        eliminarBot = new javax.swing.JButton();
        tipo2A = new javax.swing.JTextField();
        tipo3A = new javax.swing.JTextField();
        calA = new javax.swing.JTextField();
        precioA = new javax.swing.JTextField();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        obAc = new javax.swing.JComboBox<>();
        agregarBot = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        textName = new javax.swing.JLabel();
        textT1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        backg = new javax.swing.JLabel();
        crud1 = new javax.swing.JFrame();
        textT4 = new javax.swing.JLabel();
        textT5 = new javax.swing.JLabel();
        textCal1 = new javax.swing.JLabel();
        textPrice2 = new javax.swing.JLabel();
        nombreA1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        textPrice3 = new javax.swing.JLabel();
        updateBot1 = new javax.swing.JButton();
        eliminarBot1 = new javax.swing.JButton();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        obAc1 = new javax.swing.JComboBox<>();
        agregarBot1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        textName1 = new javax.swing.JLabel();
        textT6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        obAc2 = new javax.swing.JComboBox<>();
        obAc3 = new javax.swing.JComboBox<>();
        obAc4 = new javax.swing.JComboBox<>();
        obAc5 = new javax.swing.JComboBox<>();
        textT7 = new javax.swing.JLabel();
        obAc6 = new javax.swing.JComboBox<>();
        textPrice4 = new javax.swing.JLabel();
        textPrice5 = new javax.swing.JLabel();
        obAc7 = new javax.swing.JComboBox<>();
        obAc8 = new javax.swing.JComboBox<>();
        obAc9 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cliente = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jDialog2.setTitle("Opciones Admin");
        jDialog2.setMaximumSize(new java.awt.Dimension(320, 382));
        jDialog2.setMinimumSize(new java.awt.Dimension(320, 382));
        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Acompañamiento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jButton7.setText("Proteina");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 129, -1));

        jButton8.setText("Bebida");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 129, -1));

        jButton9.setText("Postre");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 129, -1));

        jButton10.setText("Plato");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 129, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ycambro/tarea2/ui/fondo2.jpg"))); // NOI18N
        jDialog2.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 380));

        jDialog2.setLocationRelativeTo(null); //Se centra
        jDialog2.setIconImage(myIcon);

        crud.setTitle("CRUDs");
        crud.setMaximumSize(new java.awt.Dimension(814, 407));
        crud.setMinimumSize(new java.awt.Dimension(814, 407));
        crud.setResizable(false);
        crud.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textT2.setForeground(new java.awt.Color(0, 0, 0));
        textT2.setText("Tipo2:");
        crud.getContentPane().add(textT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 196, -1, -1));

        textT3.setForeground(new java.awt.Color(0, 0, 0));
        textT3.setText("Tipo3:");
        crud.getContentPane().add(textT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 234, 38, -1));

        textCal.setForeground(new java.awt.Color(0, 0, 0));
        textCal.setText("Calorias:");
        crud.getContentPane().add(textCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 272, 50, -1));

        textPrice.setForeground(new java.awt.Color(0, 0, 0));
        textPrice.setText("Precio:");
        crud.getContentPane().add(textPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 310, 40, -1));

        nombreA.setBackground(java.awt.SystemColor.activeCaption);
        nombreA.setForeground(new java.awt.Color(0, 0, 0));
        nombreA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAActionPerformed(evt);
            }
        });
        crud.getContentPane().add(nombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 115, 78, -1));

        jTextField1.setBackground(java.awt.SystemColor.activeCaption);
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setMaximumSize(new java.awt.Dimension(68, 26));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        crud.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 160, 80, -1));

        tipo1A.setBackground(java.awt.SystemColor.activeCaption);
        tipo1A.setForeground(new java.awt.Color(0, 0, 0));
        crud.getContentPane().add(tipo1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 153, 78, -1));

        textPrice1.setForeground(new java.awt.Color(0, 0, 0));
        textPrice1.setText("Precio:");
        crud.getContentPane().add(textPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 165, -1, -1));

        updateBot.setText("Actualizar");
        updateBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBotActionPerformed(evt);
            }
        });
        crud.getContentPane().add(updateBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 204, -1, -1));

        eliminarBot.setText("Eliminar");
        eliminarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotActionPerformed(evt);
            }
        });
        crud.getContentPane().add(eliminarBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 159, 107, -1));

        tipo2A.setBackground(java.awt.SystemColor.activeCaption);
        tipo2A.setForeground(new java.awt.Color(0, 0, 0));
        crud.getContentPane().add(tipo2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 191, 78, -1));

        tipo3A.setBackground(java.awt.SystemColor.activeCaption);
        tipo3A.setForeground(new java.awt.Color(0, 0, 0));
        crud.getContentPane().add(tipo3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 229, 78, -1));

        calA.setBackground(java.awt.SystemColor.activeCaption);
        calA.setForeground(new java.awt.Color(0, 0, 0));
        crud.getContentPane().add(calA, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 267, 78, -1));

        precioA.setBackground(java.awt.SystemColor.activeCaption);
        precioA.setForeground(new java.awt.Color(0, 0, 0));
        crud.getContentPane().add(precioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 305, 78, -1));

        text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(0, 0, 0));
        text2.setText("Actualizar");
        crud.getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 84, -1, -1));

        text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(0, 0, 0));
        text3.setText("Ver todos");
        crud.getContentPane().add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 83, 102, -1));

        obAc.setBackground(java.awt.SystemColor.activeCaption);
        obAc.setForeground(new java.awt.Color(0, 0, 0));
        obAc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        crud.getContentPane().add(obAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 122, 115, -1));

        agregarBot.setText("Crear");
        agregarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotActionPerformed(evt);
            }
        });
        crud.getContentPane().add(agregarBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Eliminar");
        crud.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 83, -1, -1));

        text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(0, 0, 0));
        text1.setText("Crear");
        crud.getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 83, 103, -1));

        jComboBox2.setBackground(java.awt.SystemColor.activeCaption);
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        crud.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 121, 107, -1));

        textName.setForeground(new java.awt.Color(0, 0, 0));
        textName.setText("Nombre:");
        crud.getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 120, -1, -1));

        textT1.setForeground(new java.awt.Color(0, 0, 0));
        textT1.setText("Tipo1:");
        crud.getContentPane().add(textT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 158, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Classe");
        crud.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 19, 180, -1));

        jList1.setBackground(java.awt.SystemColor.activeCaption);
        jList1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        crud.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 109, 141, 216));

        backg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ycambro/tarea2/ui/fondo.jpg"))); // NOI18N
        crud.getContentPane().add(backg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 410));

        crud.setLocationRelativeTo(null); //Se centra
        crud.setIconImage(myIcon);

        crud1.setTitle("CRUDs");
        crud1.setMaximumSize(new java.awt.Dimension(814, 407));
        crud1.setMinimumSize(new java.awt.Dimension(814, 407));
        crud1.setPreferredSize(new java.awt.Dimension(814, 407));
        crud1.setResizable(false);
        crud1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textT4.setForeground(new java.awt.Color(0, 0, 0));
        textT4.setText("Acom.:");
        crud1.getContentPane().add(textT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 30));

        textT5.setForeground(new java.awt.Color(0, 0, 0));
        textT5.setText("Proteina:");
        crud1.getContentPane().add(textT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 30));

        textCal1.setForeground(new java.awt.Color(0, 0, 0));
        textCal1.setText("Postre:");
        crud1.getContentPane().add(textCal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 30));

        textPrice2.setForeground(new java.awt.Color(0, 0, 0));
        textPrice2.setText("En caloria:");
        crud1.getContentPane().add(textPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 30));

        nombreA1.setBackground(java.awt.SystemColor.activeCaption);
        nombreA1.setForeground(new java.awt.Color(0, 0, 0));
        nombreA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreA1ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(nombreA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        jTextField2.setBackground(java.awt.SystemColor.activeCaption);
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setMaximumSize(new java.awt.Dimension(68, 26));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 80, -1));

        textPrice3.setForeground(new java.awt.Color(0, 0, 0));
        textPrice3.setText("Precio:");
        crud1.getContentPane().add(textPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, 40));

        updateBot1.setText("Actualizar");
        updateBot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBot1ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(updateBot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        eliminarBot1.setText("Eliminar");
        eliminarBot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBot1ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(eliminarBot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 107, -1));

        text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text4.setForeground(new java.awt.Color(0, 0, 0));
        text4.setText("Actualizar");
        crud1.getContentPane().add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text5.setForeground(new java.awt.Color(0, 0, 0));
        text5.setText("Ver todos");
        crud1.getContentPane().add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 102, -1));

        obAc1.setBackground(java.awt.SystemColor.activeCaption);
        obAc1.setForeground(new java.awt.Color(0, 0, 0));
        obAc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        obAc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc1ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 115, -1));

        agregarBot1.setText("Crear");
        agregarBot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBot1ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(agregarBot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Eliminar");
        crud1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text6.setForeground(new java.awt.Color(0, 0, 0));
        text6.setText("Crear");
        crud1.getContentPane().add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 103, -1));

        jComboBox3.setBackground(java.awt.SystemColor.activeCaption);
        jComboBox3.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 107, -1));

        textName1.setForeground(new java.awt.Color(0, 0, 0));
        textName1.setText("Nombre:");
        crud1.getContentPane().add(textName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 20));

        textT6.setForeground(new java.awt.Color(0, 0, 0));
        textT6.setText("Tipo:");
        crud1.getContentPane().add(textT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Plato");
        crud1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 180, -1));

        jList2.setBackground(java.awt.SystemColor.activeCaption);
        jList2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList2.setForeground(new java.awt.Color(0, 0, 0));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        crud1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 141, 216));

        obAc2.setBackground(java.awt.SystemColor.activeCaption);
        obAc2.setForeground(new java.awt.Color(0, 0, 0));
        obAc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        obAc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc2ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 115, -1));

        obAc3.setBackground(java.awt.SystemColor.activeCaption);
        obAc3.setForeground(new java.awt.Color(0, 0, 0));
        obAc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        obAc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc3ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 115, -1));

        obAc4.setBackground(java.awt.SystemColor.activeCaption);
        obAc4.setForeground(new java.awt.Color(0, 0, 0));
        obAc4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        obAc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc4ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 115, -1));

        obAc5.setBackground(java.awt.SystemColor.activeCaption);
        obAc5.setForeground(new java.awt.Color(0, 0, 0));
        obAc5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        obAc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc5ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 115, -1));

        textT7.setForeground(new java.awt.Color(0, 0, 0));
        textT7.setText("Bebida:");
        crud1.getContentPane().add(textT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 50));

        obAc6.setBackground(java.awt.SystemColor.activeCaption);
        obAc6.setForeground(new java.awt.Color(0, 0, 0));
        obAc6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        obAc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc6ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 115, -1));

        textPrice4.setForeground(new java.awt.Color(0, 0, 0));
        textPrice4.setText("Vegetariano:");
        crud1.getContentPane().add(textPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 30));

        textPrice5.setForeground(new java.awt.Color(0, 0, 0));
        textPrice5.setText("Horario:");
        crud1.getContentPane().add(textPrice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 30));

        obAc7.setBackground(java.awt.SystemColor.activeCaption);
        obAc7.setForeground(new java.awt.Color(0, 0, 0));
        obAc7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alto", "Bajo" }));
        obAc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc7ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 115, -1));

        obAc8.setBackground(java.awt.SystemColor.activeCaption);
        obAc8.setForeground(new java.awt.Color(0, 0, 0));
        obAc8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desayuno", "Almuerzo", "Cena" }));
        obAc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc8ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 115, -1));

        obAc9.setBackground(java.awt.SystemColor.activeCaption);
        obAc9.setForeground(new java.awt.Color(0, 0, 0));
        obAc9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Plato con Bebida", "Combo" }));
        obAc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obAc9ActionPerformed(evt);
            }
        });
        crud1.getContentPane().add(obAc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 115, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ycambro/tarea2/ui/fondo3.jpg"))); // NOI18N
        crud1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 820, 410));

        crud1.setLocationRelativeTo(null); //Se centra
        crud1.setIconImage(myIcon);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante Saludable");
        setIconImage(myIcon);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 676));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cliente.setText("Atender");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        admin.setText("Administrar");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ycambro/tarea2/ui/gif.gif"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(820, 380));
        fondo.setMinimumSize(new java.awt.Dimension(820, 380));
        fondo.setPreferredSize(new java.awt.Dimension(820, 380));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        
    }//GEN-LAST:event_clienteActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        jDialog2.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        crud.setVisible(true);
        nombreA.setText(null);
        tipo1A.setText(null);
        tipo2A.setText(null);
        tipo3A.setText(null);
        calA.setText(null);
        precioA.setText(null);
        jTextField1.setText(null);
        jDialog2.hide();
        sepalo = "Acom";
        jLabel1.setText("Acompannamiento");
        textT1.setText("Tipo:");
        textT2.setText("Temperatura:");
        textT3.setText("Gluten:");
        jComboBox2.removeAllItems();
        obAc.removeAllItems();
        
        List<Acompannamiento> acom = AcompannamientoDAO.obtenerTodos();
        List<String> strings = new ArrayList<>();
        for (Acompannamiento acomp : acom) {
            strings.add(acomp.getNombre());
            jComboBox2.addItem(acomp.getNombre());
            obAc.addItem(acomp.getNombre());
        }
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return strings.size(); }
            @Override
            public String getElementAt(int i) { return strings.get(i); }
        });
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        crud.setVisible(true);
        nombreA.setText(null);
        tipo1A.setText(null);
        tipo2A.setText(null);
        tipo3A.setText(null);
        calA.setText(null);
        precioA.setText(null);
        jTextField1.setText(null);
        jDialog2.hide();
        sepalo = "Proteina";
        jLabel1.setText("Proteina");
        textT1.setText("Tipo:");
        textT2.setText("Origen:");
        textT3.setText("Preparación:");
        jComboBox2.removeAllItems();
        obAc.removeAllItems();
        
        List<Proteina> acom = ProteinaDAO.obtenerTodos();
        List<String> strings = new ArrayList<>();
        for (Proteina acomp : acom) {
            strings.add(acomp.getNombre());
            jComboBox2.addItem(acomp.getNombre());
            obAc.addItem(acomp.getNombre());
        }
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return strings.size(); }
            @Override
            public String getElementAt(int i) { return strings.get(i); }
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void updateBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBotActionPerformed
        if (sepalo == null) {
            System.out.println("Algo malio sal :D");
        } else if (sepalo.equals("Acom")) {
            List<Acompannamiento> acs = AcompannamientoDAO.obtenerTodos();
            for (Acompannamiento ac : acs) {
                if (ac.getNombre().equals(obAc.getSelectedItem().toString())) {
                    try {
                        ac.setPrecio(Integer.parseInt(jTextField1.getText()));
                        app.actualizarAcom(ac);
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            }
            
        } else if (sepalo.equals("Proteina")) {
            List<Proteina> acs = ProteinaDAO.obtenerTodos();
            for (Proteina ac : acs) {
                if (ac.getNombre().equals(obAc.getSelectedItem().toString())) {
                    try {
                        ac.setPrecio(Integer.parseInt(jTextField1.getText()));
                        app.actualizarProteina(ac);
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            }        
        } else if (sepalo.equals("Bebida")) {
            List<Bebida> acs = BebidaDAO.obtenerTodos();
            for (Bebida ac : acs) {
                if (ac.getNombre().equals(obAc.getSelectedItem().toString())) {
                    try {
                        ac.setPrecio(Integer.parseInt(jTextField1.getText()));
                        app.actualizarBebida(ac);
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            }
        } else if (sepalo.equals("Postre")) {
            List<Postre> acs = PostreDAO.obtenerTodos();
            for (Postre ac : acs) {
                if (ac.getNombre().equals(obAc.getSelectedItem().toString())) {
                    try {
                        ac.setPrecio(Integer.parseInt(jTextField1.getText()));
                        app.actualizarPostre(ac);
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_updateBotActionPerformed

    private void agregarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotActionPerformed
        if (sepalo == null) {
            System.out.println("Algo malio sal :D");
        } else if (sepalo.equals("Acom")) {
            app.annadirAcom(new Acompannamiento(99, nombreA.getText(), Integer.parseInt(calA.getText()), Integer.parseInt(precioA.getText()), tipo1A.getText(), tipo2A.getText(), tipo3A.getText()));
            JOptionPane.showMessageDialog(crud, "Se ha agregado con exito!");
        } else if (sepalo.equals("Proteina")) {
            app.annadirProteina(new Proteina(99, nombreA.getText(), Integer.parseInt(calA.getText()), Integer.parseInt(precioA.getText()), tipo1A.getText(), tipo2A.getText(), tipo3A.getText()));
            JOptionPane.showMessageDialog(crud, "Se ha agregado con exito!");
        } else if (sepalo.equals("Bebida")) {
            app.annadirBebida(new Bebida(99, nombreA.getText(), Integer.parseInt(calA.getText()), Integer.parseInt(precioA.getText()), tipo1A.getText(), tipo2A.getText(), tipo3A.getText()));
            JOptionPane.showMessageDialog(crud, "Se ha agregado con exito!");
        } else if (sepalo.equals("Postre")) {
            app.annadirPostre(new Postre(99, nombreA.getText(), Integer.parseInt(calA.getText()), Integer.parseInt(precioA.getText()), tipo1A.getText(), tipo2A.getText(), tipo3A.getText()));
            JOptionPane.showMessageDialog(crud, "Se ha agregado con exito!");
        }
    }//GEN-LAST:event_agregarBotActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        crud.setVisible(true);
        nombreA.setText(null);
        tipo1A.setText(null);
        tipo2A.setText(null);
        tipo3A.setText(null);
        calA.setText(null);
        precioA.setText(null);
        jTextField1.setText(null);
        jDialog2.hide();
        sepalo = "Bebida";
        jLabel1.setText("Bebida");
        textT1.setText("Tipo:");
        textT2.setText("Base:");
        textT3.setText("Temperatura:");
        jComboBox2.removeAllItems();
        obAc.removeAllItems();
        
        List<Bebida> acom = BebidaDAO.obtenerTodos();
        List<String> strings = new ArrayList<>();
        for (Bebida acomp : acom) {
            strings.add(acomp.getNombre());
            jComboBox2.addItem(acomp.getNombre());
            obAc.addItem(acomp.getNombre());
        }
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return strings.size(); }
            @Override
            public String getElementAt(int i) { return strings.get(i); }
        });
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        crud.setVisible(true);
        nombreA.setText(null);
        tipo1A.setText(null);
        tipo2A.setText(null);
        tipo3A.setText(null);
        calA.setText(null);
        precioA.setText(null);
        jTextField1.setText(null);
        jDialog2.hide();
        sepalo = "Postre";
        jLabel1.setText("Postre");
        textT1.setText("Tipo:");
        textT2.setText("Lacteo:");
        textT3.setText("Base:");
        jComboBox2.removeAllItems();
        obAc.removeAllItems();
        
        List<Postre> acom = PostreDAO.obtenerTodos();
        List<String> strings = new ArrayList<>();
        for (Postre acomp : acom) {
            strings.add(acomp.getNombre());
            jComboBox2.addItem(acomp.getNombre());
            obAc.addItem(acomp.getNombre());
        }
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return strings.size(); }
            @Override
            public String getElementAt(int i) { return strings.get(i); }
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jDialog2.hide();
        obAc4.setEnabled(false);
        obAc5.setEnabled(false);
        crud1.setVisible(true);
        jComboBox3.removeAllItems();
        obAc1.removeAllItems();
        obAc2.removeAllItems();
        obAc3.removeAllItems();
        obAc4.removeAllItems();
        obAc5.removeAllItems();
        nombreA1.setText(null);
        List<String> stringsp = new ArrayList<>();
        
        List<Acompannamiento> acom = AcompannamientoDAO.obtenerTodos();
        for (Acompannamiento acomp : acom) {
            obAc1.addItem(acomp.getNombre());
        }
        List<Proteina> prot = ProteinaDAO.obtenerTodos();
        for (Proteina acomp : prot) {
            obAc3.addItem(acomp.getNombre());
        }
        List<Bebida> bebi = BebidaDAO.obtenerTodos();
        for (Bebida acomp : bebi) {
            obAc4.addItem(acomp.getNombre());
        }
        List<Postre> post = PostreDAO.obtenerTodos();
        for (Postre acomp : post) {
            obAc5.addItem(acomp.getNombre());
        }
        
        List<Object> platos = PlatosDAO.obtenerTodos();
        for (Object acomp : platos) {
            if (acomp instanceof Plato temp) {
                obAc2.addItem(temp.getNombre());
                jComboBox3.addItem(temp.getNombre());
                stringsp.add(temp.getNombre());
            } else if (acomp instanceof PlatoBebida temp) {
                obAc2.addItem(temp.getNombre());
                jComboBox3.addItem(temp.getNombre());
                stringsp.add(temp.getNombre());
            } else if (acomp instanceof PlatoCompleto temp) {
                obAc2.addItem(temp.getNombre());
                jComboBox3.addItem(temp.getNombre());
                stringsp.add(temp.getNombre());
            }
        }
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return stringsp.size(); }
            @Override
            public String getElementAt(int i) { return stringsp.get(i); }
        });
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void eliminarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotActionPerformed
        int res = 1;
        if (sepalo == null) {
            System.out.println("Algo malio sal :D");
        } else if (sepalo.equals("Acom")) {
            List<Acompannamiento> acm = AcompannamientoDAO.obtenerTodos();
            for (Acompannamiento ac : acm) {
                if (ac.getNombre().equals(jComboBox2.getSelectedItem().toString())) {
                    res = app.eliminarAcompannamiento(ac.getId());
                    if (res == -1) {
                        JOptionPane.showMessageDialog(crud, "Esta comida esta asociado a algun plato.");
                        break;
                    } else if (res == 0) {
                        JOptionPane.showMessageDialog(crud, "Se ha eliminado con exito!");
                        break;
                    }
                }
            }
        } else if (sepalo.equals("Proteina")) {
            List<Proteina> acm = ProteinaDAO.obtenerTodos();
            for (Proteina ac : acm) {
                if (ac.getNombre().equals(jComboBox2.getSelectedItem().toString())) {
                    res = app.eliminarAcompannamiento(ac.getId());
                    if (res == -1) {
                        JOptionPane.showMessageDialog(crud, "Esta comida esta asociado a algun plato.");
                        break;
                    } else if (res == 0) {
                        JOptionPane.showMessageDialog(crud, "Se ha eliminado con exito!");
                        break;
                    }
                }
            }
        } else if (sepalo.equals("Bebida")) {
            List<Bebida> acm = BebidaDAO.obtenerTodos();
            for (Bebida ac : acm) {
                if (ac.getNombre().equals(jComboBox2.getSelectedItem().toString())) {
                    res = app.eliminarAcompannamiento(ac.getId());
                    if (res == -1) {
                        JOptionPane.showMessageDialog(crud, "Esta comida esta asociado a algun plato.");
                        break;
                    } else if (res == 0) {
                        JOptionPane.showMessageDialog(crud, "Se ha eliminado con exito!");
                        break;
                    }
                }
            }
        } else if (sepalo.equals("Postre")) {
            List<Postre> acm = PostreDAO.obtenerTodos();
            for (Postre ac : acm) {
                if (ac.getNombre().equals(jComboBox2.getSelectedItem().toString())) {
                    res = app.eliminarAcompannamiento(ac.getId());
                    if (res == -1) {
                        JOptionPane.showMessageDialog(crud, "Esta comida esta asociado a algun plato.");
                        break;
                    } else if (res == 0) {
                        JOptionPane.showMessageDialog(crud, "Se ha eliminado con exito!");
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminarBotActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void nombreAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAActionPerformed

    private void nombreA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreA1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void updateBot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBot1ActionPerformed
        List<Object> platos = PlatosDAO.obtenerTodos();
        for (Object plato : platos) {
            if (plato instanceof Plato tmp) {
                if (tmp.getNombre().equals(obAc2.getSelectedItem().toString())) {
                    try {
                        app.actualizarPlato(tmp, Integer.parseInt(jTextField2.getText()));
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            } else if (plato instanceof PlatoBebida tmp) {
                if (tmp.getNombre().equals(obAc2.getSelectedItem().toString())) {
                    try {
                        app.actualizarPlato(tmp, Integer.parseInt(jTextField2.getText()));
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            } else if (plato instanceof PlatoCompleto tmp) {
                if (tmp.getNombre().equals(obAc2.getSelectedItem().toString())) {
                    try {
                        app.actualizarPlato(tmp, Integer.parseInt(jTextField2.getText()));
                        JOptionPane.showMessageDialog(crud, "Se ha actualizado con exito!");
                        break;
                    } catch (Error e) {
                        JOptionPane.showMessageDialog(crud, "El precio debe ser un entero");
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_updateBot1ActionPerformed

    private void eliminarBot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBot1ActionPerformed
        List<Object> platos = app.getMenu().getPlatillos();
        for (Object plato : platos) {
            if (plato instanceof Plato tmp) {
                if (tmp.getNombre().equals(jComboBox3.getSelectedItem().toString())) {
                    app.eliminarPlato(tmp.getId());
                    break;
                }
            } else if (plato instanceof PlatoBebida tmp) {
                if (tmp.getNombre().equals(jComboBox3.getSelectedItem().toString())) {
                    app.eliminarPlato(tmp.getId());
                    break;
                }
            } else if (plato instanceof PlatoCompleto tmp) {
                if (tmp.getNombre().equals(jComboBox3.getSelectedItem().toString())) {
                    app.eliminarPlato(tmp.getId());
                    break;
                }
            }
        }
        app.eliminarPlato(jComboBox3.getSelectedIndex()+1);
        JOptionPane.showMessageDialog(crud1, "Plato eliminado con exito!");
    }//GEN-LAST:event_eliminarBot1ActionPerformed

    private void agregarBot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBot1ActionPerformed
        List<Acompannamiento> acomps = AcompannamientoDAO.obtenerTodos();
        List<Proteina> proteinas = ProteinaDAO.obtenerTodos();
        List<Bebida> bebidas = BebidaDAO.obtenerTodos();
        List<Postre> postres = PostreDAO.obtenerTodos();
        Acompannamiento acid = null;
        Proteina prid = null;
        Bebida beid = null;
        Postre poid = null;
        for (Acompannamiento acom : acomps) {
            if (obAc1.getSelectedItem().toString().equals(acom.getNombre())){
                acid = acom;
            }
        }
        for (Proteina acom : proteinas) {
            if (obAc1.getSelectedItem().toString().equals(acom.getNombre())){
                prid = acom;
            }
        }
        if (obAc9.getSelectedIndex() == 0) {
            app.annadirPlato(new Plato(99, nombreA1.getText(), obAc9.getSelectedIndex()+1, acid, prid, (acid.getCalorias() + prid.getCalorias()), (acid.getPrecio() + prid.getPrecio()), obAc7.getSelectedItem().toString(), obAc6.getSelectedItem().toString(), obAc8.getSelectedItem().toString()));
        } else if (obAc9.getSelectedIndex() == 1) {
            for (Bebida acom : bebidas) {
                if (obAc1.getSelectedItem().toString().equals(acom.getNombre())){
                    beid = acom;
                }
            }
            app.annadirPlato(new PlatoBebida(99, nombreA1.getText(), obAc9.getSelectedIndex()+1, acid, prid, beid, (acid.getCalorias() + prid.getCalorias()), (acid.getPrecio() + prid.getPrecio()), obAc7.getSelectedItem().toString(), obAc6.getSelectedItem().toString(), obAc8.getSelectedItem().toString()));
        } else if (obAc9.getSelectedIndex() == 2) {
            for (Bebida acom1 : bebidas) {
                if (obAc1.getSelectedItem().toString().equals(acom1.getNombre())){
                    beid = acom1;
                }
            }
            for (Postre acom : postres) {
                if (obAc1.getSelectedItem().toString().equals(acom.getNombre())){
                    poid = acom;
                }
            }
            app.annadirPlato(new PlatoCompleto(99, nombreA1.getText(), obAc9.getSelectedIndex()+1, acid, prid, beid, poid, (acid.getCalorias() + prid.getCalorias()), (acid.getPrecio() + prid.getPrecio()), obAc7.getSelectedItem().toString(), obAc6.getSelectedItem().toString(), obAc8.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_agregarBot1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void obAc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc1ActionPerformed

    private void obAc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc2ActionPerformed

    private void obAc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc3ActionPerformed

    private void obAc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc4ActionPerformed

    private void obAc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc5ActionPerformed

    private void obAc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc6ActionPerformed

    private void obAc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc7ActionPerformed

    private void obAc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obAc8ActionPerformed

    private void obAc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obAc9ActionPerformed
        if (obAc9.getSelectedIndex() == 0) {
            obAc4.setEnabled(false);
            obAc5.setEnabled(false);
        } else if (obAc9.getSelectedIndex() == 1) {
            obAc4.setEnabled(true);
            obAc5.setEnabled(false);
        } else if (obAc9.getSelectedIndex() == 2) {
            obAc4.setEnabled(true);
            obAc5.setEnabled(true);
        }
    }//GEN-LAST:event_obAc9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton agregarBot;
    private javax.swing.JButton agregarBot1;
    private javax.swing.JLabel backg;
    private javax.swing.JTextField calA;
    private javax.swing.JButton cliente;
    private javax.swing.JFrame crud;
    private javax.swing.JFrame crud1;
    private javax.swing.JButton eliminarBot;
    private javax.swing.JButton eliminarBot1;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombreA;
    private javax.swing.JTextField nombreA1;
    private javax.swing.JComboBox<String> obAc;
    private javax.swing.JComboBox<String> obAc1;
    private javax.swing.JComboBox<String> obAc2;
    private javax.swing.JComboBox<String> obAc3;
    private javax.swing.JComboBox<String> obAc4;
    private javax.swing.JComboBox<String> obAc5;
    private javax.swing.JComboBox<String> obAc6;
    private javax.swing.JComboBox<String> obAc7;
    private javax.swing.JComboBox<String> obAc8;
    private javax.swing.JComboBox<String> obAc9;
    private javax.swing.JTextField precioA;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel textCal;
    private javax.swing.JLabel textCal1;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textName1;
    private javax.swing.JLabel textPrice;
    private javax.swing.JLabel textPrice1;
    private javax.swing.JLabel textPrice2;
    private javax.swing.JLabel textPrice3;
    private javax.swing.JLabel textPrice4;
    private javax.swing.JLabel textPrice5;
    private javax.swing.JLabel textT1;
    private javax.swing.JLabel textT2;
    private javax.swing.JLabel textT3;
    private javax.swing.JLabel textT4;
    private javax.swing.JLabel textT5;
    private javax.swing.JLabel textT6;
    private javax.swing.JLabel textT7;
    private javax.swing.JTextField tipo1A;
    private javax.swing.JTextField tipo2A;
    private javax.swing.JTextField tipo3A;
    private javax.swing.JButton updateBot;
    private javax.swing.JButton updateBot1;
    // End of variables declaration//GEN-END:variables
}
